### ISSUE TITLE
Unrecognized command line option: mindirect-branc=thunk

### ISSUE THREAD

**Issue by eduran0826** [bashrc/libdeep#11]
When trying to compile the code through `make` I receive the following error:

> gcc: error: unrecognized command line option 'mindirect-branch=thunk'; did you mean -findirect-inlining'?

After replacing all instances of 'mindirect-branch=thunk' in the Makefiles with -findirect-inlining' libdeep successfully compiles and all the unit tests pass. 

I am on Ubuntu 16.04 with gcc version 7.2.0

I have never encountered this issue and I wanted to verify that this is a necessary and safe fix before creating a pull request. 

![mindirect-branch](https://user-images.githubusercontent.com/12473592/36295450-476b9874-12ad-11e8-8d32-4d958335158f.png)

**Comment by bashrc** [comment]
This compiler option is the recommended mitigation for meltdown/spectre, and I think it's only available in a recent version of gcc. I'm currently using 7.3.0.

**Comment by eduran0826** [comment]
Ah okay understood. Thanks for the information @bashrc. I will update my compiler. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
