### ISSUE TITLE
Making sense of xor example results

### ISSUE THREAD

**Issue by melvincabatuan** [bashrc/libdeep#5]
Hi,

Thank you for this library.

I have compiled the xor example here:

https://gist.github.com/melvincabatuan/453571d20f29d4fcce27

with a test performance of:

    Test data set performance is 99.3%

However, when I run the generated network the TRUE activation seems to
settle at approx. 0.238 value while FALSE at 0.289 and 0.200?
 
Is this the correct interpretation of this sample run or am I misunderstanding this result?

E.g.
```shell
# gcc -Wall -lm export_xor.c -o export_xor
# ls
export_xor  export_xor.c  export_xor.py  Makefile  training.png  xor  xor.c  xor.data
# ./export_xor 0 0
0.2899920344
# ./export_xor 0 1
0.2375777960
# ./export_xor 1 1
0.2001982927
# ./export_xor 1 0
0.2378264666
```

**Comment by bashrc** [comment]
This does seem rather curious. I'll have to check it.

**Comment by bashrc** [comment]
It's just that the xor test is has a text based data set (see xor.data), so the inputs should be text. I've added a test script called test.sh which illustrates this.

**Comment by melvincabatuan** [comment]
Thanks
